theme = "native"
icons = "awesome"

[[block]]
block = "cpu"
interval = 1
format = "{frequency}GHz {barchart} {utilization}%"

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{max}°"
chip = "*-isa-*"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mupi}%"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 10.0
alert = 5.0

[[block]]
block = "net"
format = "{ssid} {signal_strength}"
interval = 5
use_bits = false

[[block]]
block = "sound"

[[block]]
block = "battery"
interval = 10
format = "{percentage}%"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
